server:
  port: 7070
spring:
  application:
    name: wmh-member
  cloud:
    nacos:
      discovery:
        ##nacos服务注册地址
        server-addr: 127.0.0.1:8848

###若在swagger类中开启@EnableSwaggerBootstrapUI 账户权限配置，请开启一下配置
#swagger:
#  production: false
#  basic:
#    enable: true
#    username: admin
#    password: admin
